### ISSUE TITLE
Github Page로 공개 안하나요

### ISSUE THREAD

**Issue by kpjhg0124** [kdo9921/miliday#1]
봐보고싶네

**Comment by kdo9921** [comment]
예전에 했다가 지금은 https://apteryx.moe로 옮겼습니다. 이 래포같은경우 https://apteryx.moe/miliday 에 있습니다

**Comment by kdo9921** [comment]
깃헙 페이지 다른용도로 쓰려고 예전부터 생각은 해놨는데 귀찮아서 자꾸 미루고있네요ㅎㅎ
